#!/usr/bin/env python3

# Set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
# Configuración del archivo odoo.conf por defecto
__import__('os').environ['ODOO_RC'] = 'odoo.conf'  
import odoo

if __name__ == "__main__":
    odoo.cli.main()